/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import actores.*;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.Timer;

/**
 *
 * @authors:
 * Jhonnier Hernandez
 * Juan Cifuentes
 * Alejandra Carvajal
 */
public class VentanaJuego extends javax.swing.JFrame {
    
    /**
     * Creates new form VentanaJuego
     */
    private Ronda ronda;
    public static Jugador jugador = new Jugador();
    private Figura figuraReto;
    private List<javax.swing.JLabel> listaLabelsFichas = new ArrayList<>() {{ add(lblFicha1); add(lblFicha2); add(lblFicha3); 
    add(lblFicha4); add(lblFicha5); add(lblFicha6); add(lblFicha7); add(lblFicha8); add(lblFicha9); add(lblFicha10);
    add(lblFicha11); add(lblFicha12); add(lblFicha13); add(lblFicha14); add(lblFicha15); add(lblFicha16); add(lblFicha17);
    add(lblFicha18); add(lblFicha19); add(lblFicha20); add(lblFicha21); add(lblFicha22); add(lblFicha23);
    add(lblFicha24); add(lblFicha25); add(lblFicha26); add(lblFicha27); add(lblFicha28); add(lblFicha29); add(lblFicha30);
    add(lblFicha31); add(lblFicha32); add(lblFicha33); add(lblFicha34); add(lblFicha35); add(lblFicha36);}};
    private List<Figura> figuras = new ArrayList<>();
    
    private boolean rondaIniciada; 
    private boolean rondaFinalizada;
    private boolean fichasClickeables;

    private int tiempoDeObservacion;
    private Timer contador;
    
    private JuegoMemorable juego;
    
    
    public VentanaJuego() {
        ronda = new Ronda();
        figuraReto = new Figura();
        rondaIniciada = false;
        rondaFinalizada = false;
        fichasClickeables = true;
        
        tiempoDeObservacion = 5;
        contador = new Timer (1000, new ActionListener ()
        {
            public void actionPerformed(ActionEvent e)
            {
                tiempoDeObservacion--;
                lblContador.setText("|"+tiempoDeObservacion);
                if (tiempoDeObservacion == 0)
                {
                    /*contador.stop();
                    lblFicha1.setIcon(null);
                    lblFicha2.setIcon(null);
                    lblFicha3.setIcon(null);
                    while (((figuraReto.getRutaDeImagen() != figura1.getRutaDeImagen()) && (figuraReto.getRutaDeImagen() != figura2.getRutaDeImagen()) && (figuraReto.getRutaDeImagen() != figura3.getRutaDeImagen())) || (figuraReto.getRutaDeImagen() == null)){
                        figuraReto.setRutaDeImagen();
                    }
                    figuraReto.setRutaDeImagenTo(lblFichaReto);
                    juego.contarNumeroDeFigurasAEncontrar(figura1, figura2, figura3, figuraReto);

                    fichasClickeables = true;*/
                }
            }
        });
        
        juego = new JuegoMemorable(jugador);
        
                
        initComponents();
        for(int i = 0; i < listaLabelsFichas.size(); i++){
            Figura figuraX = new Figura();
            figuras.add(figuraX);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFicha1 = new javax.swing.JLabel();
        lblFicha2 = new javax.swing.JLabel();
        lblFicha3 = new javax.swing.JLabel();
        lblFicha4 = new javax.swing.JLabel();
        lblFicha5 = new javax.swing.JLabel();
        lblFicha6 = new javax.swing.JLabel();
        lblFicha7 = new javax.swing.JLabel();
        lblFicha8 = new javax.swing.JLabel();
        lblFicha9 = new javax.swing.JLabel();
        lblFicha10 = new javax.swing.JLabel();
        lblFicha11 = new javax.swing.JLabel();
        lblFicha12 = new javax.swing.JLabel();
        lblFicha13 = new javax.swing.JLabel();
        lblFicha14 = new javax.swing.JLabel();
        lblFicha15 = new javax.swing.JLabel();
        lblFicha16 = new javax.swing.JLabel();
        lblFicha17 = new javax.swing.JLabel();
        lblFicha18 = new javax.swing.JLabel();
        lblFicha19 = new javax.swing.JLabel();
        lblFicha20 = new javax.swing.JLabel();
        lblFicha21 = new javax.swing.JLabel();
        lblFicha22 = new javax.swing.JLabel();
        lblFicha23 = new javax.swing.JLabel();
        lblFicha24 = new javax.swing.JLabel();
        lblFicha25 = new javax.swing.JLabel();
        lblFicha26 = new javax.swing.JLabel();
        lblFicha27 = new javax.swing.JLabel();
        lblFicha28 = new javax.swing.JLabel();
        lblFicha29 = new javax.swing.JLabel();
        lblFicha30 = new javax.swing.JLabel();
        lblFicha31 = new javax.swing.JLabel();
        lblFicha32 = new javax.swing.JLabel();
        lblFicha33 = new javax.swing.JLabel();
        lblFicha34 = new javax.swing.JLabel();
        lblFicha35 = new javax.swing.JLabel();
        lblFicha36 = new javax.swing.JLabel();
        lblVida3 = new javax.swing.JLabel();
        lblVida2 = new javax.swing.JLabel();
        lblVida1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        lblFichaReto = new javax.swing.JLabel();
        contenedorPpal = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFicha1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha1MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 82, 70, 70));

        lblFicha2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha2MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 82, 70, 70));

        lblFicha3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha3MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 82, 70, 70));

        lblFicha4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha4MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 82, 70, 70));

        lblFicha5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha5MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 82, 70, 70));

        lblFicha6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha6MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 82, 70, 70));

        lblFicha7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha7MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha7, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 82, 70, 70));

        lblFicha8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha8MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 82, 70, 70));

        lblFicha9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha9MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 82, 70, 70));

        lblFicha10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha10MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha10, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 158, 70, 70));

        lblFicha11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha11MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha11, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 158, 70, 70));

        lblFicha12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha12MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha12, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 158, 70, 70));

        lblFicha13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha13MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha13, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 158, 70, 70));

        lblFicha14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha14MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha14, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 158, 70, 70));

        lblFicha15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha15MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha15, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 158, 70, 70));

        lblFicha16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha16MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha16, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 158, 70, 70));

        lblFicha17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha17MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha17, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 158, 70, 70));

        lblFicha18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha18MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha18, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 158, 70, 70));

        lblFicha19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha19MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha19, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 236, 70, 70));

        lblFicha20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha20MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha20, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 236, 70, 70));

        lblFicha21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha21MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha21, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 236, 70, 70));

        lblFicha22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha22MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha22, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 236, 70, 70));

        lblFicha23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha23MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha23, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 236, 70, 70));

        lblFicha24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha24MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha24, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 236, 70, 70));

        lblFicha25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha25MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha25, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 236, 70, 70));

        lblFicha26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha26MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha26, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 236, 70, 70));

        lblFicha27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha27MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha27, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 236, 70, 70));

        lblFicha28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha28MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha28, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 313, 70, 70));

        lblFicha29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha29MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha29, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 313, 70, 70));

        lblFicha30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha30MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha30, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 313, 70, 70));

        lblFicha31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha31MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha31, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 313, 70, 70));

        lblFicha32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha32MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha32, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 313, 70, 70));

        lblFicha33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha33MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha33, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 313, 70, 70));

        lblFicha34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha34MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha34, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 313, 70, 70));

        lblFicha35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha35MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha35, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 313, 70, 70));

        lblFicha36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFicha36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFicha36MouseClicked(evt);
            }
        });
        getContentPane().add(lblFicha36, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 313, 70, 70));

        lblVida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vidas/corazonSi.png"))); // NOI18N
        getContentPane().add(lblVida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 17, 40, 40));

        lblVida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vidas/corazonSi.png"))); // NOI18N
        getContentPane().add(lblVida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 17, 40, 40));

        lblVida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vidas/corazonSi.png"))); // NOI18N
        getContentPane().add(lblVida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 17, 40, 40));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText(jugador.getNombre());
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 370, 40));

        lblJugador.setFont(new java.awt.Font("Malgun Gothic", 0, 30)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugador.setText("JUGADOR: ");
        getContentPane().add(lblJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 40));

        lblContador.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblContador.setForeground(new java.awt.Color(255, 0, 0));
        lblContador.setText("|"+tiempoDeObservacion);
        getContentPane().add(lblContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 410, 70, 70));
        getContentPane().add(lblFichaReto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 100, 170));

        contenedorPpal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background/ventanaJuego.png"))); // NOI18N
        contenedorPpal.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(contenedorPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFicha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha1MouseClicked

    private void lblFicha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha2MouseClicked

    private void lblFicha3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha3MouseClicked

    private void lblFicha4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha4MouseClicked

    private void lblFicha5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha5MouseClicked

    private void lblFicha6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha6MouseClicked

    private void lblFicha7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha7MouseClicked

    private void lblFicha8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha8MouseClicked

    private void lblFicha9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha9MouseClicked

    private void lblFicha10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha10MouseClicked

    private void lblFicha11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha11MouseClicked

    private void lblFicha12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha12MouseClicked

    private void lblFicha13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha13MouseClicked

    private void lblFicha14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha14MouseClicked

    private void lblFicha15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha15MouseClicked

    private void lblFicha16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha16MouseClicked

    private void lblFicha17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha17MouseClicked

    private void lblFicha18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha18MouseClicked

    private void lblFicha19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha19MouseClicked

    private void lblFicha20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha20MouseClicked

    private void lblFicha21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha21MouseClicked

    private void lblFicha22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha22MouseClicked

    private void lblFicha23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha23MouseClicked

    private void lblFicha24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha24MouseClicked

    private void lblFicha25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha25MouseClicked

    private void lblFicha26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha26MouseClicked

    private void lblFicha27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha27MouseClicked

    private void lblFicha28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha28MouseClicked

    private void lblFicha29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha29MouseClicked

    private void lblFicha30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha30MouseClicked

    private void lblFicha31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha31MouseClicked

    private void lblFicha32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha32MouseClicked

    private void lblFicha33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha33MouseClicked

    private void lblFicha34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha34MouseClicked

    private void lblFicha35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha35MouseClicked

    private void lblFicha36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFicha36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFicha36MouseClicked

    /** Funcion general para todos las fichas.
       Si se da click a una ficha y este es clickeable se ejecuta, si no es clickeable no se ejecuta.
        - Si se ejecuta se evalua si la ronda ya ha iniciado o no:
         - Si la ronda no ha iniciado, se inicia la ronda.
         - Si la ronda ya ha iniciado, se muestra la figura que esconde la ficha y determina si la ronda debe continuar o finalizar.
    */
    public void lblFichaXMouseClicked(javax.swing.JLabel lblFichaX, Figura figuraX) {
        if (fichasClickeables){
            if(rondaIniciada == false){
                fichasClickeables = false;
                iniciarRonda();
            }
            else{
                if (!figuraX.getFiguraObservada() && figuraX.getRutaDeImagen() != null){
                    figuraX.observarFigura();
                    
                    mostrarFichaYCompararFigura(lblFichaX,figuraX);
                    
                    finalizarOContinuarRonda(figuraX);
                }
            }
        }
    }
    
    // Pone el juego como si no hubiera iniciado la ronda. Este metodo se ejecuta cuando se acaba una ronda
    public void establecerElementosComoDeInicioDeRonda(){
        System.out.println("Juego Terminado");
        rondaIniciada = false;
        //rondaFinalizada = false;
        //fichasClickeables = true;
        tiempoDeObservacion = 5;
        lblFicha1.setIcon(null);
        lblFicha2.setIcon(null);
        lblFicha3.setIcon(null);
        lblFichaReto.setIcon(null);
        figuraReto.setRutaDeImagen();
    }
    
    // Inicia una nueva ronda. Este metodo se ejecuta cuando se requiere iniciar otra ronda
    public void iniciarRonda(){
        rondaIniciada = true;
        ronda.mas1NumeroDeRonda();
        figurasAMostrar();
        contador.start();
    }

    // Muestra la figura que contiene la ficha y compara si es la que se esta pidiendo. Este metodo se ejecuta cuando se le da click a una ficha despues de terminado el contador
    public void mostrarFichaYCompararFigura(javax.swing.JLabel lblFichaX, Figura figuraX){
        figuraX.setRutaDeImagenTo(lblFichaX);
        String icono = figuraX.getRutaDeImagen();
        String iconoComparar = figuraReto.getRutaDeImagen();
        if(icono.equals(iconoComparar)){
            System.out.println("Acertaste!");
        }else{
            System.out.println("Fallaste!");
        }
        System.out.println("icono = " + icono);
        System.out.println("iconoComparar = " + iconoComparar);
    }

    // Finaliza una ronda si ya se encontraron todas las fichas con la descripcion dada. Este metodo se ejecuta cuando se le da click a una ficha despues de terminado el contador
    public void finalizarOContinuarRonda(Figura figuraX){
        rondaFinalizada = juego.todasLasFichasSeleccionadas(figuraX, figuraReto);
        if (rondaFinalizada == true){
            establecerElementosComoDeInicioDeRonda();
        }
    }
    
    // Establece que figuras y sobre que fichas se van a mostrar (Nota: cada tres rondas se muestra una figura mas). Este metodo se ejecuta cuando se inicia una ronda
    public void figurasAMostrar(){
        
        figura1.anularRutaDeImagen(lblFicha1);
        figura2.anularRutaDeImagen(lblFicha2);
        figura3.anularRutaDeImagen(lblFicha3);
        
        boolean figura1Seted = false;
        boolean figura2Seted = false;
        boolean figura3Seted = false;
        
        int figurasSeted = 0;
        
        if ((ronda.getNumeroDeRonda() >= 1) && (ronda.getNumeroDeRonda() < 4)) {
            int numeroRandom2 = (int) (Math.random()*3);
            if (!figura1Seted && numeroRandom2 == 0){
                figura1.setRutaDeImagen();
                figura1.setRutaDeImagenTo(lblFicha1);
                figura1Seted = true;
                figurasSeted++;
            } else if (!figura2Seted && numeroRandom2 == 1){
                figura2.setRutaDeImagen();
                figura2.setRutaDeImagenTo(lblFicha2);
                figura2Seted = true;
                figurasSeted++;
            } else if (!figura3Seted && numeroRandom2 == 2){
                figura3.setRutaDeImagen();
                figura3.setRutaDeImagenTo(lblFicha3);
                figura3Seted = true;
                figurasSeted++;
            }

//            int numeroRandom2;
//            while (figurasSeted < 1){
//                numeroRandom2 = (int) (Math.random()*3);
//                ArrayList<Integer> listaDeNumeros = new ArrayList<>();
//                if (!listaDeNumeros.contains(numeroRandom2)){
//                    listaDeNumeros.add(numeroRandom2);
//                    System.out.println("PTM");
//                    figura[numeroRandom2].setRutaDeImagen();
//                    System.out.println("PTM");
//                    figura[numeroRandom2].setRutaDeImagenTo(lblFicha[numeroRandom2]);
//                    System.out.println("PTM");
//                    figurasSeted++;
//                }
//            }
        } else if ((ronda.getNumeroDeRonda() >= 4) && (ronda.getNumeroDeRonda() < 7)) {
            while (figurasSeted < 2){
                int numeroRandom2 = (int) (Math.random()*3);
                if (!figura1Seted && numeroRandom2 == 0){
                    figura1.setRutaDeImagen();
                    figura1.setRutaDeImagenTo(lblFicha1);
                    figura1Seted = true;
                    figurasSeted++;
                } else if (!figura2Seted && numeroRandom2 == 1){
                    figura2.setRutaDeImagen();
                    figura2.setRutaDeImagenTo(lblFicha2);
                    figura2Seted = true;
                    figurasSeted++;
                } else if (!figura3Seted && numeroRandom2 == 2){
                    figura3.setRutaDeImagen();
                    figura3.setRutaDeImagenTo(lblFicha3);
                    figura3Seted = true;
                    figurasSeted++;
                }
            }
            
//            while (figurasSeted < 2){
//                int numeroRandom2 = (int) (Math.random()*3);
//                ArrayList<Integer> listaDeNumeros = new ArrayList<>();
//                if (!listaDeNumeros.contains(numeroRandom2)){
//                    listaDeNumeros.add(numeroRandom2);
//                    figura[numeroRandom2].setRutaDeImagen();
//                    figura[numeroRandom2].setRutaDeImagenTo(lblFicha[numeroRandom2]);
//                    figurasSeted++;
//                }
//            }
        } else if ((ronda.getNumeroDeRonda() >= 7) && (ronda.getNumeroDeRonda() < 10)) {
            figura1.setRutaDeImagen();
            figura1.setRutaDeImagenTo(lblFicha1);
            figura2.setRutaDeImagen();
            figura2.setRutaDeImagenTo(lblFicha2);
            figura3.setRutaDeImagen();
            figura3.setRutaDeImagenTo(lblFicha3);

//            int numeroRandom2;
//            while (figurasSeted < 3){
//                numeroRandom2 = (int) (Math.random()*3);
//                ArrayList<Integer> listaDeNumeros = new ArrayList<>();
//                if (!listaDeNumeros.contains(numeroRandom2)){
//                    listaDeNumeros.add(numeroRandom2);
//                    figura[numeroRandom2].setRutaDeImagen();
//                    figura[numeroRandom2].setRutaDeImagenTo(lblFicha[numeroRandom2]);
//                    figurasSeted++;
//                }
//            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPpal;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblFicha1;
    private javax.swing.JLabel lblFicha10;
    private javax.swing.JLabel lblFicha11;
    private javax.swing.JLabel lblFicha12;
    private javax.swing.JLabel lblFicha13;
    private javax.swing.JLabel lblFicha14;
    private javax.swing.JLabel lblFicha15;
    private javax.swing.JLabel lblFicha16;
    private javax.swing.JLabel lblFicha17;
    private javax.swing.JLabel lblFicha18;
    private javax.swing.JLabel lblFicha19;
    private javax.swing.JLabel lblFicha2;
    private javax.swing.JLabel lblFicha20;
    private javax.swing.JLabel lblFicha21;
    private javax.swing.JLabel lblFicha22;
    private javax.swing.JLabel lblFicha23;
    private javax.swing.JLabel lblFicha24;
    private javax.swing.JLabel lblFicha25;
    private javax.swing.JLabel lblFicha26;
    private javax.swing.JLabel lblFicha27;
    private javax.swing.JLabel lblFicha28;
    private javax.swing.JLabel lblFicha29;
    private javax.swing.JLabel lblFicha3;
    private javax.swing.JLabel lblFicha30;
    private javax.swing.JLabel lblFicha31;
    private javax.swing.JLabel lblFicha32;
    private javax.swing.JLabel lblFicha33;
    private javax.swing.JLabel lblFicha34;
    private javax.swing.JLabel lblFicha35;
    private javax.swing.JLabel lblFicha36;
    private javax.swing.JLabel lblFicha4;
    private javax.swing.JLabel lblFicha5;
    private javax.swing.JLabel lblFicha6;
    private javax.swing.JLabel lblFicha7;
    private javax.swing.JLabel lblFicha8;
    private javax.swing.JLabel lblFicha9;
    private javax.swing.JLabel lblFichaReto;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblVida1;
    private javax.swing.JLabel lblVida2;
    private javax.swing.JLabel lblVida3;
    // End of variables declaration//GEN-END:variables
}
