/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @authors:
 * Jhonnier Hernandez
 * Juan Cifuentes
 * Alejandra Carvajal
 */
import actores.Jugador;
public class ventanaDatos extends javax.swing.JFrame {

    /**
     * Creates new form ventanaDatos
     */
    public ventanaDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresoNombre = new javax.swing.JLabel();
        txtIngresoNombre = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresoNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        ingresoNombre.setForeground(new java.awt.Color(0, 102, 51));
        ingresoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresoNombre.setText("INGRESE SU NOMBRE");
        getContentPane().add(ingresoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 430, 50));

        txtIngresoNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        txtIngresoNombre.setForeground(new java.awt.Color(0, 102, 102));
        txtIngresoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIngresoNombre.setText("JUGADOR 1");
        txtIngresoNombre.setCaretColor(new java.awt.Color(255, 255, 204));
        txtIngresoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtIngresoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 300, -1));

        btnOk.setBackground(new java.awt.Color(255, 255, 204));
        btnOk.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        btnOk.setForeground(new java.awt.Color(0, 102, 51));
        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresoNombreActionPerformed

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkMouseClicked

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String nombreJugador = txtIngresoNombre.getText();
        Jugador jugador1 = new Jugador (nombreJugador);
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaDatos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel ingresoNombre;
    private javax.swing.JTextField txtIngresoNombre;
    // End of variables declaration//GEN-END:variables
}
