/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author aleja
 */
public class VentanaContinuarJugando extends javax.swing.JFrame {

    /**
     * Creates new form VentanaContinuarJugando
     */
    public VentanaContinuarJugando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deseaContinuarJugando = new javax.swing.JLabel();
        siContinuar = new javax.swing.JButton();
        noContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        deseaContinuarJugando.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        deseaContinuarJugando.setForeground(new java.awt.Color(0, 102, 51));
        deseaContinuarJugando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deseaContinuarJugando.setText("¿DESEA VOLVER A JUGAR?");

        siContinuar.setBackground(new java.awt.Color(204, 255, 204));
        siContinuar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        siContinuar.setForeground(new java.awt.Color(102, 102, 0));
        siContinuar.setText("SI");
        siContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siContinuarActionPerformed(evt);
            }
        });

        noContinuar.setBackground(new java.awt.Color(255, 153, 153));
        noContinuar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        noContinuar.setForeground(new java.awt.Color(102, 102, 0));
        noContinuar.setText("NO");
        noContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deseaContinuarJugando, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(siContinuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noContinuar)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(deseaContinuarJugando)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siContinuar)
                    .addComponent(noContinuar))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siContinuarActionPerformed

        VentanaInicio newframe = new VentanaInicio();

        newframe.setVisible(true);
        
        this.dispose();

    }//GEN-LAST:event_siContinuarActionPerformed

    private void noContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noContinuarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_noContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaContinuarJugando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaContinuarJugando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaContinuarJugando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaContinuarJugando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaContinuarJugando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deseaContinuarJugando;
    private javax.swing.JButton noContinuar;
    private javax.swing.JButton siContinuar;
    // End of variables declaration//GEN-END:variables
}
